cd backend;
echo "1";
npm i;
echo "2";
cd ..;
echo "3"
cd frontend;
echo "4";
npm i;
echo "5";
cd ..;
echo "6";
mkdir backend/data;
echo "7";
cp backend/sampledata/data.db backend/data/data.db;
echo "8";
cp -a backend/sampledata/uploads/. backend/public/uploads;
echo "9";
echo -en "DATABASE_FILENAME=data/data.db\nADMIN_JWT_SECRET=$(openssl rand -hex 16)" >backend/.env;
echo "10";